SYMBOL_SPOT = "XAUUSD=X"
SYMBOL_FUTURES = "GC=F"

TIMEFRAMES = {
    "15m": {"period": "60d", "interval": "15m"},
    "5m": {"period": "60d", "interval": "5m"},
    "1m": {"period": "7d", "interval": "1m"},
}

ATR_PERIOD = 14
SWING_LEFT = 2
SWING_RIGHT = 2

# Structure confirmation
MIN_BREAK_ATR = 0.15
MIN_DISPLACEMENT_BODY = 0.55
DISPLACEMENT_ATR = 0.80

# Liquidity / zones
EQUAL_LEVEL_ATR = 0.12
SWEEP_MIN_ATR = 0.05
MIN_FVG_ATR = 0.08
OB_LOOKAHEAD = 3

# Signal gates
MIN_SIGNAL = 75
MIN_WATCH = 60
MAX_NEWS_RISK_FOR_ENTRY = 55
MAX_SIGNAL_AGE_BARS = 3

# Trade construction
SL_ATR_BUFFER = 0.15
MIN_RISK_ATR = 0.60
MAX_RISK_ATR = 2.50
TP1_R = 1.0
TP2_R = 2.0

# News
NEWS_MAX_AGE_HOURS = 36
HIGH_IMPACT_WINDOW_MIN = 30
ELEVATED_IMPACT_WINDOW_MIN = 90


# Validation / backtest
BACKTEST_MIN_BARS = 600
BACKTEST_HORIZON_BARS = 24
BACKTEST_STEP_BARS = 1
BACKTEST_OOS_FRACTION = 0.30
BACKTEST_MIN_TRADES = 20

# Session windows in UTC (gold scalp focus)
LONDON_START_UTC = 7
LONDON_END_UTC = 11
NEW_YORK_START_UTC = 13
NEW_YORK_END_UTC = 17
